apiVersion: nfd.openshift.io/v1
kind: NodeFeatureDiscovery
metadata:
  name: nfd-instance
  namespace: openshift-nfd
spec:
  operand:
    image: >-
      registry.redhat.io/openshift4/ose-node-feature-discovery@sha256:ac5ae9290b02e6d2c50d86b2f4a6bcf623fe47428388ba04cef530bf9f5110f4
    servicePort: 12000
  workerConfig:
    configData: |
      core:
        sleepInterval: 60s
      sources:
        pci:
          deviceClassWhitelist:
            - "0200"
            - "03"
            - "12"
          deviceLabelFields:
            - "vendor"
